#!/bin/sh

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.0
* initial 'echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version.js
* added changelog to deploy
 
'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.1
* added ime/gen/'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.2
* added provider based file system
* added rrsp.dll
* fixed inner window width 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.2.1
* added support for multiple disks 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.3
* added lssp.dll
* added fs.delete
* added fs.rename
* added fs.mime
* fixed window buttons
* fixed desktop icon sizes
* fixed cursor image

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.4
* added memdog.exe
* added import to desktop
* fixed rename for binary data

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.5
* replaced lssp.dll with stzr.dll
* fixed async fs calls
* added interaction.lock 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6
* added tray

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6.1
* added index.php rendering in deploy 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6.2
* added ray rendering to deploy

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6.3
* added automatic tests 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'versions export

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6.4
* changed win-'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6.5
* added cover to screenshots 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6.5.1
* fixed cover screenshot size

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6.5.2
* fixed cover size again 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6.6
* added buildtime to gen configs 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6.6.1
* fixed buildtime

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.6.6.2
* fixed buildtime again 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7
* removed non-windows content

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.1
* removed more theoffice content
* fixed screenshotting

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.2
* added wininfo.exe 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.2.1
* fixed wininfo path

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.2.2
* added reset to reset all gen vars 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.2.3
* fixed deploy order

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.2.4
* fixed wininfo size 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.3
* added globalConsole.output
* added console output logging

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.3.1
* added testing/programs 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.4
* added logo to wininfo

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.4.1
* added file info to wininfo 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.4.2
* added tests

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.4.3
* fixed tests

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.4.4
* fixed test path 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.4.5
* fixed test parameter passing

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.4.6
* fixed test paths

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.7.4.7
* removed memdog 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8
* removed meta420.exe
* removed utilman.exe (old testing program)
* added processes
* added taskmgr.exe

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.0.1
* removed taskmgr.exe from autorun
* fixed wininfo.exe 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.1
* added old scrollbars to browser
* fixed window bottom padding 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.1.1
* added windows log output in deploy 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.1.2
* fixed log output 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.1.3
* formatted log output 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.1.4
* added log output color to deploy 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.1.5
* added earlier log output in deploy 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.1.6
* reverted 0.0.8.1.5 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2
* added timer tracking to process
* added process tab to taskmgr.exe
* added tooltips
* added providerOf to fs
* added datagrid to ui 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version issue 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.1
* fixed '

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version issue 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.2
* fixed '

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.3
* removed deploy automagic 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.4
* fixed taskmgr not showing anything initially 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.5
* added more testing options

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.6
* fixed tests/programs 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.7
* moved cover windows 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.8
* moved cover windows 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.9
* moved cover windows 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.9.1
* moved cover windows 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.9.2
* added waiting for window to test 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.9.3
* fixed waiting 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.2.9.4
* moved cover windows 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.3
* added query parameter rrsp
* added win-roots
* fixed autogens 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.4
* removed devenv.exe (moved to dev root) 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.8.4.1
* removed icosurf from tests 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9
* added nogap
* added tray icons
* minor changes 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.1
* fixed taskbar size 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.2
* added process error
* added window render error 
* added application error

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.3
* added dynamic css files (csc) 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.3.1
* added selective font download forcing

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.3.2
* added beta specific font loading 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'versions 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.3.3
* added latest to win-'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.4
* added favicon
* fixed issues when using corssdomain rrsps
* added config/init loading

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.4.1
* updated screenshot size 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.4.2
* added screenshot delay 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.4.3
* fixed screenshot delay 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.4.4
* fixed screenshot delay 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.5
* added exe meta 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.5.1
* fixed tests 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.5.2
* removed netyrn from tests 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.6
* added dll meta 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7
* added scopetransform
* added application.persistentState 
* added process.state
* added .meta
* removed old icons
* added management
* removed config
* added menu to explorer.exe
* added custom cursor

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7.1
* moved .meta
* added drag and drop (explorer and backres) 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7.1.1
* added directory metas to some directories
* removed assembly/ the office leftovers 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7.1.2
* added scaled fonts 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7.1.3
* removed scaled fonts temporarily 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7.1.4
* added gen/.prop files for easier parsing of env values
* cleanup index.php 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7.1.5
* fixed scopetransform source atob/btoa error 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7.1.6
* added isNaN, isFinite, NaN and Array to application env
* added undefined and null handler in scopetransform 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7.1.7
* fixed url encoding in queryconf 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7.1.7.2
* added assert.dll
* added assert tests 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.7.1.7.3
* fixed assert test export

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.8
* added page favicon
* added dynamic page title
* moved back to black and white console
* added noLinkIcon meta property to desktop 
* added threading
* added taskmgr tray icon
* fixed cursors
* added application.run cursor 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.9
* moved c/windows/csc to dlls (/styles)
* moved evals to <scripts> in document head
* improved error reporting
* moved path operations to Path
* moved fs access to async functions
* added File class
* moved fs.icon to Icon
* added process/shell output
* added color console to cmd
* fixed a ton of bugs 
* removed program tests

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.9.1
* added microsoft license to winver (design)

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.9.2
* added Management.device.size
* added automatic window maximizing in smaller sizes 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.9.3
* added application main function
* added scopetransform debug logging
* added services.exe
* added installer.exe
* added wizard
* added hubs
* added ftp storage provider
* added usage information 
* added help.exe
* added msi installers 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.9.4
* removed scoped env
* improved application speed
* removed utm tracking
* small fixes 
* added better loading info for non-beta boot builds

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.9.4.1
* fixed bsod when ftpsp fails to connect
* fixed bsod not showing output when in non beta build
* changed beta wallpaper color
* added build info in beta 

'

echo "pseudo-commit $RANDOM" > pseudo-commit
git add pseudo-commit
git commit -m 'version 0.0.9.9.4.2
* minor fixes 

'